Repository SOPT-36-NINEDOT/NINEDOT-SERVER, pull requests merged in 2025-07, with the labels that each got.

#5 [Feat] #4: 초기 세팅
  .gitignore
  build.gradle
  src/main/java/org/sopt36/ninedotserver/global/config/jpa/JpaAuditingConfig.java
  src/main/java/org/sopt36/ninedotserver/global/config/security/SecurityConfig.java
  src/main/java/org/sopt36/ninedotserver/global/config/swagger/SwaggerConfig.java
  src/main/java/org/sopt36/ninedotserver/global/dto/response/ApiResponse.java
  src/main/java/org/sopt36/ninedotserver/global/dto/response/ErrorMeta.java
  src/main/java/org/sopt36/ninedotserver/global/entity/BaseEntity.java
  src/main/java/org/sopt36/ninedotserver/global/exception/BusinessException.java
  src/main/java/org/sopt36/ninedotserver/global/exception/ErrorCode.java
  src/main/java/org/sopt36/ninedotserver/global/exception/GlobalErrorCode.java
  src/main/java/org/sopt36/ninedotserver/global/exception/GlobalExceptionHandler.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ FEAT, 🐶 소연 🐶

#8 [FEAT] 프로젝트 초기 세팅 main에 merge
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/org/sopt36/ninedotserver/global/config/jpa/JpaAuditingConfig.java
  src/main/java/org/sopt36/ninedotserver/global/config/security/SecurityConfig.java
  src/main/java/org/sopt36/ninedotserver/global/config/swagger/SwaggerConfig.java
  src/main/java/org/sopt36/ninedotserver/global/dto/response/ApiResponse.java
  src/main/java/org/sopt36/ninedotserver/global/dto/response/ErrorMeta.java
  src/main/java/org/sopt36/ninedotserver/global/entity/BaseEntity.java
  src/main/java/org/sopt36/ninedotserver/global/exception/BusinessException.java
  src/main/java/org/sopt36/ninedotserver/global/exception/ErrorCode.java
  src/main/java/org/sopt36/ninedotserver/global/exception/GlobalErrorCode.java
  src/main/java/org/sopt36/ninedotserver/global/exception/GlobalExceptionHandler.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ FEAT, 🐶 소연 🐶

#10 [FIX] #9: cors, swagger 오류 해결
  src/main/java/org/sopt36/ninedotserver/global/config/security/SecurityConfig.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/application-prod.yml
Labels: 🐶 소연 🐶, 🐞 BUG

#21 [FEAT] #16: User, RefreshToken, AuthProvider 엔티티 생성
  build.gradle
  src/main/java/org/sopt36/ninedotserver/auth/domain/AuthProvider.java
  src/main/java/org/sopt36/ninedotserver/auth/domain/ProviderType.java
  src/main/java/org/sopt36/ninedotserver/auth/domain/RefreshToken.java
  src/main/java/org/sopt36/ninedotserver/user/domain/JobType.java
  src/main/java/org/sopt36/ninedotserver/user/domain/User.java
  src/main/java/org/sopt36/ninedotserver/user/exception/UserErrorCode.java
Labels: ✨ FEAT, 🥵 승준 🥵

#25 [FEAT] #23: update user/auth entity
  src/main/java/org/sopt36/ninedotserver/auth/domain/AuthProvider.java
  src/main/java/org/sopt36/ninedotserver/auth/domain/RefreshToken.java
  src/main/java/org/sopt36/ninedotserver/user/domain/User.java
Labels: ✨ FEAT, 🥵 승준 🥵

#20 [FEAT] #18: Mandalart(mandalart, CoreGoal, SubGoal, History) entity 생성
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/CoreGoal.java
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/Cycle.java
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/History.java
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/Mandalart.java
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/SubGoal.java
  src/main/java/org/sopt36/ninedotserver/mandalart/exception/CoreGoalErrorCode.java
  src/main/java/org/sopt36/ninedotserver/mandalart/exception/MandalartErrorCode.java
  src/main/java/org/sopt36/ninedotserver/mandalart/exception/SubGoalErrorCode.java
Labels: ✨ FEAT, ♥️ 찬민 ♥️

#32 [FEAT] #31: 만다라트(전체 목표) 생성
  src/main/java/org/sopt36/ninedotserver/global/dto/response/ApiResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/MandalartController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/MandalartMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/request/MandalartCreateRequest.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/request/tmp.txt
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/MandalartCreateResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/MandalartCommandService.java
  src/main/java/org/sopt36/ninedotserver/user/exception/UserErrorCode.java
Labels: ✨ FEAT, 🐶 소연 🐶

#35 [FEAT] #27: create core goals
  src/main/java/org/sopt36/ninedotserver/global/exception/GlobalErrorCode.java
  src/main/java/org/sopt36/ninedotserver/global/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/CoreGoalController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/CoreGoalMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/Mandalart.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/request/CoreGoalCreateRequest.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/CoreGoalCreateResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/tmp.txt
  src/main/java/org/sopt36/ninedotserver/mandalart/exception/CoreGoalErrorCode.java
  src/main/java/org/sopt36/ninedotserver/mandalart/exception/MandalartErrorCode.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/CoreGoalRepository.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/CoreGoalCommandService.java
  src/main/java/org/sopt36/ninedotserver/user/domain/User.java
Labels: ✨ FEAT, 🐶 소연 🐶

#37 [FEAT] #29: 상위 목표 id 리스트 반환
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/CoreGoalController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/CoreGoalMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/CoreGoalIdResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/CoreGoalIdsResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/CoreGoalRepository.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/CoreGoalCommandService.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/query/CoreGoalQueryService.java
Labels: ✨ FEAT, 🐶 소연 🐶

#41 Feat/#36 만다라트 하위 목표 생성
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/SubGoalController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/SubGoalMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/SubGoal.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/request/SubGoalCreateRequest.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/SubGoalCreateResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/exception/SubGoalErrorCode.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalRepository.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/SubGoalCommandService.java
Labels: ✨ FEAT, ♥️ 찬민 ♥️

#52 [FEAT] #50: 온보딩 시 상위 목표 수정
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/CoreGoalController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/CoreGoalMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/CoreGoal.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/request/CoreGoalUpdateRequest.java
  src/main/java/org/sopt36/ninedotserver/mandalart/exception/CoreGoalErrorCode.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/CoreGoalCommandService.java
Labels: ✨ FEAT, 🐶 소연 🐶

#56 [FEAT] #51: 온보딩 시 상위 목표 삭제 api 구현
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/CoreGoalController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/SubGoalController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/CoreGoalMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalRepository.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalSnapshotRepository.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/CoreGoalCommandService.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/SubGoalCommandService.java
Labels: ✨ FEAT, 🐶 소연 🐶

#60 [FEAT] #59: 하위 목표 완료 체크
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/HistoryController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/HistoryMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/exception/HistoryErrorCode.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/HistoryRepository.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/HistoryCommandService.java
Labels: ✨ FEAT, 🐶 소연 🐶

#65 [FEAT] #61 페르소나 맞춤 정보 질문 리스트 반환 api 구현
  src/main/java/org/sopt36/ninedotserver/ai/dto/request/SubGoalAiRequest.java
  src/main/java/org/sopt36/ninedotserver/ai/dto/request/SubGoalTitleRequest.java
  src/main/java/org/sopt36/ninedotserver/ai/dto/request/tmp.txt
  src/main/java/org/sopt36/ninedotserver/ai/dto/response/SubGoalAiResponse.java
  src/main/java/org/sopt36/ninedotserver/ai/dto/response/SubGoalTitleResponse.java
  src/main/java/org/sopt36/ninedotserver/ai/util/PromptBuilder.java
  src/main/java/org/sopt36/ninedotserver/global/config/gemini/GeminiConfig.java
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/Cycle.java
  src/main/java/org/sopt36/ninedotserver/onboarding/controller/QuestionController.java
  src/main/java/org/sopt36/ninedotserver/onboarding/controller/message/QuestionMessage.java
  src/main/java/org/sopt36/ninedotserver/onboarding/domain/Type.java
  src/main/java/org/sopt36/ninedotserver/onboarding/dto/request/tmp.txt
  src/main/java/org/sopt36/ninedotserver/onboarding/dto/response/PersonaQuestionResponse.java
  src/main/java/org/sopt36/ninedotserver/onboarding/dto/response/QuestionResponse.java
  src/main/java/org/sopt36/ninedotserver/onboarding/dto/response/tmp.txt
  src/main/java/org/sopt36/ninedotserver/onboarding/exception/QuestionErrorCode.java
  src/main/java/org/sopt36/ninedotserver/onboarding/repository/ChoiceRepository.java
  src/main/java/org/sopt36/ninedotserver/onboarding/repository/QuestionRepository.java
  src/main/java/org/sopt36/ninedotserver/onboarding/repository/QuestionRepositoryCustom.java
  src/main/java/org/sopt36/ninedotserver/onboarding/repository/QuestionRepositoryImpl.java
  src/main/java/org/sopt36/ninedotserver/onboarding/service/query/QuestionQueryService.java
Labels: ✨ FEAT, ♥️ 찬민 ♥️

#63 [FEAT] #62: 하위 목표 완료 취소
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/HistoryController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/HistoryMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/exception/HistoryErrorCode.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/HistoryRepository.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/HistoryCommandService.java
Labels: ✨ FEAT, 🐶 소연 🐶

#67 [FEAT] #66: 만다라트 대목표 조회
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/MandalartController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/MandalartMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/MandalartResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/query/MandalartQueryService.java
Labels: ✨ FEAT, 🥵 승준 🥵

#45 [FEAT] #26: 구글 소셜로그인 구현
  .github/workflows/deploy-prod.yml
  build.gradle
  src/main/java/org/sopt36/ninedotserver/auth/controller/AuthController.java
  src/main/java/org/sopt36/ninedotserver/auth/controller/message/AuthMessage.java
  src/main/java/org/sopt36/ninedotserver/auth/domain/AuthProvider.java
  src/main/java/org/sopt36/ninedotserver/auth/domain/OnboardingPage.java
  src/main/java/org/sopt36/ninedotserver/auth/dto/request/GoogleAuthCodeRequest.java
  src/main/java/org/sopt36/ninedotserver/auth/dto/request/tmp.txt
  src/main/java/org/sopt36/ninedotserver/auth/dto/response/GoogleTokenResponse.java
  src/main/java/org/sopt36/ninedotserver/auth/dto/response/GoogleUserInfo.java
  src/main/java/org/sopt36/ninedotserver/auth/dto/response/LoginOrSignupResponse.java
  src/main/java/org/sopt36/ninedotserver/auth/dto/response/tmp.txt
  src/main/java/org/sopt36/ninedotserver/auth/exception/AuthErrorCode.java
  src/main/java/org/sopt36/ninedotserver/auth/exception/AuthException.java
  src/main/java/org/sopt36/ninedotserver/auth/repository/AuthProviderRepository.java
  src/main/java/org/sopt36/ninedotserver/auth/service/AuthService.java
  src/main/java/org/sopt36/ninedotserver/global/config/auth/AuthConfig.java
  src/main/java/org/sopt36/ninedotserver/global/config/security/JwtProvider.java
  src/main/java/org/sopt36/ninedotserver/global/config/security/SecurityConfig.java
  src/main/java/org/sopt36/ninedotserver/global/config/security/TokenAuthenticationFilter.java
  src/main/java/org/sopt36/ninedotserver/global/exception/BusinessException.java
  src/main/java/org/sopt36/ninedotserver/global/util/CookieUtil.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/CoreGoalRepositoryCustom.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/CoreGoalRepositoryImpl.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/MandalartRepositoryCustom.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/MandalartRepositoryImpl.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalRepositoryCustom.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalRepositoryImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ✨ FEAT, 🥵 승준 🥵

#79 [FEAT] #72: 스트릭 트래커 반환
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/HistoryController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/CoreGoalMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/HistoryMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/StreakListResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/StreakResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/TodoResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/HistoryRepository.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/query/HistoryQueryService.java
Labels: ✨ FEAT, 🐶 소연 🐶

#75 [FEAT] #74: 회원가입 시 직업 드롭다운 반환
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/CoreGoalRepositoryImpl.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/MandalartRepositoryImpl.java
  src/main/java/org/sopt36/ninedotserver/onboarding/controller/QuestionController.java
  src/main/java/org/sopt36/ninedotserver/onboarding/controller/message/QuestionMessage.java
  src/main/java/org/sopt36/ninedotserver/onboarding/dto/response/JobDropdownResponse.java
  src/main/java/org/sopt36/ninedotserver/onboarding/exception/QuestionErrorCode.java
  src/main/java/org/sopt36/ninedotserver/onboarding/repository/ChoiceRepositoryCustom.java
  src/main/java/org/sopt36/ninedotserver/onboarding/repository/ChoiceRepositoryImpl.java
  src/main/java/org/sopt36/ninedotserver/onboarding/service/query/QuestionQueryService.java
Labels: ✨ FEAT, 🥵 승준 🥵

#77 [FEAT] #76: 유저 정보 조회
  src/main/java/org/sopt36/ninedotserver/user/controller/UserController.java
  src/main/java/org/sopt36/ninedotserver/user/controller/message/UserMessage.java
  src/main/java/org/sopt36/ninedotserver/user/dto/response/UserInfoResponse.java
  src/main/java/org/sopt36/ninedotserver/user/dto/response/tmp.txt
  src/main/java/org/sopt36/ninedotserver/user/service/query/UserQueryService.java
Labels: ✨ FEAT, 🥵 승준 🥵

#92 [FEAT] #91: 만다라트 보드 전체 조회
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/MandalartController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/MandalartMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/CoreGoalBoardResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/MandalartBoardResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/SubGoalBoardResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalSnapshotRepositoryCustom.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalSnapshotRepositoryImpl.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/query/MandalartQueryService.java
Labels: ✨ FEAT, 🐶 소연 🐶

#93 [FEAT] #87: 하위목표 추천값 ai에 추가
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/SubGoalController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/message/SubGoalMessage.java
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/Cycle.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/request/SubGoalAiCreateRequest.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/request/SubGoalAiListCreateRequest.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/SubGoalAiListResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/SubGoalAiResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/exception/SubGoalErrorCode.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalSnapshotRepositoryCustom.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalSnapshotRepositoryImpl.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/SubGoalCommandService.java
Labels: ✨ FEAT, 🐶 소연 🐶

#101 [HOTFIX] #99: deploy-prod.yml 수정
  .github/workflows/deploy-prod.yml
Labels: ✨ FEAT, 🐶 소연 🐶

#104 [HOTFIX] #103: cicd 수정
  .github/workflows/deploy-prod.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🐶 소연 🐶, 🐞 BUG

#107 [HOTFIX] #105: ci 문법 오류 수정
  src/main/resources/application-prod.yml
Labels: 🐶 소연 🐶, 🐞 BUG

#109 [HOTFIX] #108: : build.gradle 수정
  build.gradle
Labels: 🐶 소연 🐶, 🐞 BUG

#113 [FEAT] #112: 배포 환경 스케쥴러 확인
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/RecommendationSchedulerService.java
Labels: ✨ FEAT, 🐶 소연 🐶

#119 [FIX] #116: 스케쥴러 시간대 오류 수정
  src/main/java/org/sopt36/ninedotserver/mandalart/service/command/RecommendationSchedulerService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 🐶 소연 🐶, 🐞 BUG

#125 [HOTFIX] #124: cors에 프론트 dev 배포 주소 추가
  src/main/java/org/sopt36/ninedotserver/global/config/security/SecurityConfig.java
Labels: 🐶 소연 🐶, 🐞 BUG

#127 Feat/#123 give profile image
  src/main/java/org/sopt36/ninedotserver/ai/service/AiRecommendationService.java
  src/main/java/org/sopt36/ninedotserver/auth/dto/response/LoginOrSignupResponse.java
  src/main/java/org/sopt36/ninedotserver/auth/service/AuthService.java
  src/main/java/org/sopt36/ninedotserver/onboarding/repository/AnswerRepository.java
Labels: 🥵 승준 🥵

#131 [HOTFIX] #130: 하위 목표 ai 생성 시 상위 목표 검증 로직 오류 수정
  src/main/java/org/sopt36/ninedotserver/ai/service/AiSubGoalRecommendationService.java
Labels: ✨ FEAT, 🐶 소연 🐶

#133 [HOTFIX] #132: 하위 목표 ai 생성 시 엔드포인트 오류 수정
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/SubGoalController.java
Labels: 🐶 소연 🐶, 🐞 BUG

#139 [FIX] (#136/mandalart): sub goal position 순서대로 반환, 날짜별로 반환,완료여부도 반환
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/RecommendationController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/SubGoalController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/dto/response/SubGoalDetailResponse.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalSnapshotRepositoryCustom.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/SubGoalSnapshotRepositoryImpl.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/query/RecommendationQueryService.java
  src/main/java/org/sopt36/ninedotserver/mandalart/service/query/SubGoalQueryService.java
Labels: enhancement, 🥵 승준 🥵

#146 [FIX] #145: 서버 시간대 오류 수정
  Dockerfile
  docker-compose.dev.yml
  docker-compose.prod.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ✨ FEAT, 🐶 소연 🐶

#117 refactor(#46/ai): ai generatable 여부 검증 추가
  src/main/java/org/sopt36/ninedotserver/ai/exception/AiErrorCode.java
  src/main/java/org/sopt36/ninedotserver/ai/service/AiRecommendationService.java
  src/main/java/org/sopt36/ninedotserver/ai/service/AiSubGoalRecommendationService.java
  src/main/java/org/sopt36/ninedotserver/mandalart/controller/CoreGoalController.java
  src/main/java/org/sopt36/ninedotserver/mandalart/domain/Mandalart.java
Labels: enhancement, 🥵 승준 🥵

#151 [FIX] #150: 하위 목표 ai 생성 시 검증 오류 수정
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/MandalartRepositoryCustom.java
  src/main/java/org/sopt36/ninedotserver/mandalart/repository/MandalartRepositoryImpl.java
Labels: 🐶 소연 🐶, 🐞 BUG

#158 [FEAT] README.md 추가
  README.md
Labels: ✨ FEAT, 🐶 소연 🐶
